
POST http://localhost:3002/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:3002/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "87495b95-1c7f-4038-ae55-ab36ed6a9411"
}

###

POST http://localhost:3002/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "account_id_to": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    "amount": 100
}

###

GET http://localhost:3003/balances/bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb HTTP/1.1